server:
  port: 8080

spring:
  application:
    name: challenge
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:rate-limit}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/tenpo_db_challenge}
    username: ${SPRING_DATASOURCE_USERNAME:tenpo_db_user}
    password: ${SPRING_DATASOURCE_PASSWORD:tenpo_db_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.tenpo.challenge.controller